package net.heronation.zeyo.rest.integrate.controller.cafe24.dto;

import lombok.Data; 

@Data
public class OrderItem {
      private String item_no;
      private String order_item_code;
      private String variant_code;
      private String product_no;
      private String product_code;
      private String eng_product_name;
      private String option_id;
      private String option_value;
      private String option_value_default;
      private String additional_option_value;
      private String product_name;
      private String product_name_default;
      private String product_price;
      private String option_price;
      private String additional_discount_price;
      private String quantity;
      private String supplier_product_name;
      private String supplier_transaction_type;
      private String supplier_id;
      private String supplier_name;
      private String tracking_no;
      private String shipping_code;
      private String post_express_flag;
      private String order_status;
      private String order_status_additional_info;
      private String status_code;
      private String status_text;
      private String open_market_status;
      private String bundled_shipping_type;
      private String shipping_company_id;
      private String shipping_company_name;
      private String shipping_company_code;
      private String product_bundle;
      private String product_bundle_no;
      private String product_bundle_name;
      private String product_bundle_name_default;
      private String product_bundle_type;
      private String was_product_bundle;
      private String original_bundle_item_no;
      private String naver_pay_order_id;
      private String naver_pay_claim_status;
      private String individual_shipping_fee;
      private String shipping_fee_type;
      private String shipping_fee_type_text;
      private String payment_info_id;
      private String original_item_no;
      private String store_pickup;
      private String ordered_date;
      private String shipped_date;
      private String delivered_date;
      private String cancel_date;
      private String return_request_date;
      private String return_date;
      private String cancel_request_date;
      private String refund_date;
      private String exchange_request_date;
      private String exchange_date;
      private String product_material;
      private String product_material_eng;
      private String cloth_fabric;
      private String product_weight;
      private String volume_size;
      private String volume_size_weight;
      private String clearance_category;
      private String clearance_category_info;
      private String clearance_category_code;
      private String hs_code;
      private String one_plus_n_event;
      private String origin_place;
      private String gift;
}
